/**
 * Lengine Security Research Mindmap: CSRF (Origin-Context Confusion)
 *
 * Modeled as an expert field notebook / second brain for security researchers.
 * Emphasizes investigation questions, observable signals, discriminating experiments,
 * causal reconstruction, and capability boundaries rather than passive definitions.
 */

export interface MindmapNode {
  id: string;
  label: string;
  category: 'ROOT' | 'OBSERVE' | 'ASK' | 'HYPOTHESIZE' | 'TEST' | 'EVIDENCE' | 'RECONSTRUCT' | 'CAPABILITY' | 'TRANSFER';
  parentId?: string;
  tagline: string;
  thinkAbout: string[];
  diagnosticQuestions: string[];
  evidenceToInspect: {
    title: string;
    type: 'http' | 'headers' | 'cookies' | 'dom' | 'checklist';
    snippet: string;
  }[];
  discriminatingExperiment?: {
    action: string;
    predictionIfTrue: string;
    predictionIfFalse: string;
    whyInformative: string;
  };
  pitfalls: string[];
  canonicalReference?: {
    conceptOrMechanism: string;
    whyItMatters: string;
  };
}

export const CSRF_MINDMAP_DATA: {
  topic: {
    id: string;
    name: string;
    subtitle: string;
    mechanismFamily: string;
  };
  nodes: MindmapNode[];
} = {
  topic: {
    id: 'topic.csrf',
    name: 'Cross-Site Request Forgery (CSRF)',
    subtitle: 'Origin-Context Confusion & Ambient Authority Investigation Map',
    mechanismFamily: 'mechanism.origin-context-confusion'
  },
  nodes: [
    // ROOT
    {
      id: 'root',
      label: 'CSRF Investigation Core',
      category: 'ROOT',
      tagline: 'How an experienced researcher determines whether an endpoint is vulnerable to cross-site dispatch',
      thinkAbout: [
        'Do not ask "Is this CSRF?" Ask "Can an external origin cause the victim\'s browser to execute this action under the victim\'s authority?"',
        'Separation of concerns: Identity (who holds the session) vs. Intent (what context originated the request).',
        'Same-Origin Policy asymmetry: SOP restricts cross-origin response reading, but permits cross-origin request transmission (writes).'
      ],
      diagnosticQuestions: [
        'Does the target HTTP endpoint perform an impactful server-side state mutation?',
        'Does the application rely on ambient credentials (cookies, Basic auth, TLS certs)?',
        'Does the endpoint lack unpredictable, origin-bound proof of user intent?',
        'Can cross-origin requests dispatch without being blocked by browser SameSite policies or Fetch Metadata?'
      ],
      evidenceToInspect: [
        {
          title: 'Target Endpoint Archetype',
          type: 'http',
          snippet: `POST /api/profile/email HTTP/1.1\nHost: app.local\nCookie: session_id=sess_user_9921\nOrigin: https://app.local\nContent-Type: application/x-www-form-urlencoded\n\nemail=victim_updated@app.local`
        }
      ],
      pitfalls: [
        'Prematurely reporting CSRF on idempotent GET requests or search queries with no state impact.',
        'Assuming the presence of a "csrf_token" form field proves protection without differential testing.'
      ]
    },

    // 1. OBSERVE (What can I see?)
    {
      id: 'obs_request',
      parentId: 'root',
      label: 'Request & Method',
      category: 'OBSERVE',
      tagline: 'Inspect the HTTP verb, path, and content-type of the state-changing action',
      thinkAbout: [
        'Is the action executed over POST, PUT, DELETE, or GET?',
        'Is Content-Type a simple type (application/x-www-form-urlencoded, multipart/form-data, text/plain)? Simple types can be submitted across origins via standard HTML forms without CORS preflight (OPTIONS).',
        'If Content-Type is application/json, does the endpoint accept form-encoded or text/plain payloads as fallback?'
      ],
      diagnosticQuestions: [
        'Can this request be generated by a standard <form action="..." method="POST"> without JavaScript access?',
        'Does the application reject non-POST methods, or does a method override parameter (e.g. _method=POST or switching to GET) bypass checks?'
      ],
      evidenceToInspect: [
        {
          title: 'Inspect Request Headers',
          type: 'headers',
          snippet: `Content-Type: application/x-www-form-urlencoded\nAccept: application/json, text/plain, */*\nHost: app.local`
        }
      ],
      pitfalls: [
        'Assuming JSON endpoints are automatically safe without testing Content-Type leniency or Flash/parser quirks.'
      ]
    },
    {
      id: 'obs_credentials',
      parentId: 'root',
      label: 'Credential Mechanism',
      category: 'OBSERVE',
      tagline: 'Determine if authority is ambient (browser-managed) or explicit (script-managed)',
      thinkAbout: [
        'Ambient credentials: Cookies, HTTP Basic/Digest authentication, TLS client certificates. Attached automatically by the browser to all matching destination hosts.',
        'Explicit credentials: Authorization: Bearer <token> stored in JavaScript memory or Web Storage. The browser NEVER automatically attaches explicit headers on cross-origin form dispatches.',
        'Inspect Set-Cookie attributes: SameSite=Strict, SameSite=Lax, or SameSite=None.'
      ],
      diagnosticQuestions: [
        'Is the user identified by a Cookie header or an Authorization header?',
        'Does Set-Cookie declare SameSite=Strict, or does it omit SameSite (defaulting to Lax in Chromium)?',
        'Was the session cookie set within the last 120 seconds (Chromium Lax-allowing-unsafe window)?'
      ],
      evidenceToInspect: [
        {
          title: 'Cookie Jar Analysis',
          type: 'cookies',
          snippet: `Set-Cookie: session_id=sess_user_9921; Path=/; HttpOnly; SameSite=None; Secure\n# If SameSite=None -> sent on all cross-site requests\n# If omitted -> default Lax (withheld on cross-site POST after 2 min)`
        }
      ],
      pitfalls: [
        'Confusing HttpOnly with CSRF defense. HttpOnly stops JavaScript from reading document.cookie (defending against XSS theft); it has zero effect on cross-origin cookie attachment!'
      ],
      canonicalReference: {
        conceptOrMechanism: 'concept.ambient-credentials',
        whyItMatters: 'Ambient credentials turn the browser network engine into a Confused Deputy for third-party scripts.'
      }
    },
    {
      id: 'obs_provenance',
      parentId: 'root',
      label: 'Origin & Referer Headers',
      category: 'OBSERVE',
      tagline: 'Examine whether the client sends and the server inspects origin metadata',
      thinkAbout: [
        'Origin header: Included by browsers on cross-origin requests, POST requests, and CORS fetches. Cannot be modified or forged by client-side JavaScript (forbidden header).',
        'Referer header: Includes the full or partial URL of the referring page; can be stripped via Referrer-Policy: no-referrer.',
        'Sec-Fetch-Site header: Browser-managed metadata (same-origin, same-site, cross-site, none).'
      ],
      diagnosticQuestions: [
        'Does the server inspect the Origin header?',
        'What happens if the Origin header points to https://evil.example?',
        'What happens if the Origin and Referer headers are completely stripped?'
      ],
      evidenceToInspect: [
        {
          title: 'Browser Provenance Headers',
          type: 'headers',
          snippet: `Origin: https://app.local\nReferer: https://app.local/settings/profile\nSec-Fetch-Site: same-origin\nSec-Fetch-Mode: cors\nSec-Fetch-Dest: empty`
        }
      ],
      pitfalls: [
        'Regex validation flaws on Origin (e.g. checking if Origin contains "app.local", which attacker bypasses via "app.local.attacker.com" or "attacker-app.local").'
      ]
    },
    {
      id: 'obs_state_delta',
      parentId: 'root',
      label: 'State Mutation',
      category: 'OBSERVE',
      tagline: 'Verify whether the endpoint commits persistent side effects',
      thinkAbout: [
        'A security vulnerability requires a meaningful state delta or authority transition.',
        'Sensitive targets: email change, password update, API token generation, 2FA toggle, money transfer, address update.',
        'Safe/idempotent endpoints (search, read-only analytics) do not produce CSRF impact because the Same-Origin Policy blocks evil.com from reading the response body.'
      ],
      diagnosticQuestions: [
        'Did the database or backend state actually change after the request?',
        'Does the state change affect the victim account permanently or temporarily?'
      ],
      evidenceToInspect: [
        {
          title: 'Observable State Transition',
          type: 'http',
          snippet: `HTTP/1.1 200 OK\nContent-Type: application/json\n\n{"status":"success","user":{"email":"attacker_target@test.local"}}`
        }
      ],
      pitfalls: [
        'Assuming a 200 OK means state changed without independently verifying backend persistence.'
      ]
    },

    // 2. ASK (Inquire)
    {
      id: 'ask_control',
      parentId: 'root',
      label: 'Who Controls the Input?',
      category: 'ASK',
      tagline: 'Map which parts of the request can be synthesized by an external caller',
      thinkAbout: [
        'Attacker on evil.com can specify: HTTP Method (GET, POST), URL parameters, form body fields, destination path.',
        'Attacker CANNOT specify: Victim\'s Cookie values (if cookies are HttpOnly or not accessible across origins), custom request headers (unless CORS allows), or unguessable random tokens generated in victim DOM.'
      ],
      diagnosticQuestions: [
        'Can an attacker hosted on an unrelated domain construct all required body parameters without knowing victim secrets?'
      ],
      evidenceToInspect: [
        {
          title: 'Attacker Coercion Vector',
          type: 'dom',
          snippet: `<form action="https://app.local/api/profile/email" method="POST">\n  <input type="hidden" name="email" value="hacker@evil.com" />\n</form>\n<script>document.forms[0].submit();</script>`
        }
      ],
      pitfalls: [
        'Overlooking secondary confirmation prompts or CAPTCHAs that disrupt automated coercion.'
      ]
    },
    {
      id: 'ask_authority',
      parentId: 'root',
      label: 'Who Supplies Authority?',
      category: 'ASK',
      tagline: 'Identify the exact trust transformation between caller and credentials',
      thinkAbout: [
        'The victim\'s browser runtime acts as a Confused Deputy: it holds authority (valid session cookies) and lends that authority to instructions drafted by an untrusted origin.',
        'The receiving server evaluates identity (who owns the session) but fails to evaluate provenance (what origin initiated the action).'
      ],
      diagnosticQuestions: [
        'Does the application distinguish between "The user is logged in" and "The user deliberately initiated this action from our legitimate interface"?'
      ],
      evidenceToInspect: [
        {
          title: 'Confused Deputy Diagram',
          type: 'checklist',
          snippet: `[Attacker Page (evil.com)] -> Initiates form POST\n        |\n[Victim Browser] -> Injects Cookie: session_id=XYZ (Ambient Authority)\n        |\n[Target Server] -> Validates cookie -> Executes mutation (Conflates identity with intent)`
        }
      ],
      pitfalls: [
        'Assuming strong password hashing or multi-factor authentication at login protects subsequent requests from ambient credential abuse.'
      ]
    },
    {
      id: 'ask_boundary',
      parentId: 'root',
      label: 'What Boundary is Crossed?',
      category: 'ASK',
      tagline: 'Trace data flow across web origin boundaries',
      thinkAbout: [
        'Trust boundary: Between the untrusted origin (evil.com) and the victim\'s trusted session context.',
        'Same-Origin Policy allows requests across origins by default; it only restricts reading response data.'
      ],
      diagnosticQuestions: [
        'Does the request cross from external origin to target origin without entering a re-authentication or step-up verification barrier?'
      ],
      evidenceToInspect: [
        {
          title: 'Origin Boundary Crossing',
          type: 'headers',
          snippet: `Source Context: https://evil.com (Untrusted Origin)\nTarget Context: https://app.local/api/profile/email (Authenticated Sink)\nBoundary Control: None (Missing anti-CSRF token / SameSite=None)`
        }
      ],
      pitfalls: [
        'Believing SOP protects against requests being dispatched.'
      ]
    },

    // 3. HYPOTHESIZE (Compete)
    {
      id: 'hyp_competing',
      parentId: 'root',
      label: 'Competing Explanations',
      category: 'HYPOTHESIZE',
      tagline: 'Formulate falsifiable explanations before running experiments',
      thinkAbout: [
        'Never jump to "It is vulnerable!" Formulate at least two mutually exclusive, testable hypotheses regarding how the server processes the request.',
        'H1: Session-Only Validation (Server checks session cookie only; ignores origin/referer; requires no intent token).',
        'H2: Origin/Referer Allowlist Enforcement (Server validates Origin/Referer header against allowed domains).',
        'H3: Token Omission Flaw (Server generates tokens in HTML forms, but only validates if parameter is present).',
        'H4: Method-Switching Flaw (Token validation enforced on POST, bypassed when toggled to GET).'
      ],
      diagnosticQuestions: [
        'What observation would prove H1 true and H2 false?',
        'What observation would prove H3 true and H1 false?'
      ],
      evidenceToInspect: [
        {
          title: 'Hypothesis Decision Matrix',
          type: 'checklist',
          snippet: `Hypothesis A: Server enforces zero origin validation.\nHypothesis B: Server requires Origin/Referer matching app.local.\nHypothesis C: Server requires a valid CSRF token but omits check on method switch.`
        }
      ],
      pitfalls: [
        'Single-hypothesis fixation (confirmation bias): only testing things that confirm your initial suspicion.'
      ]
    },

    // 4. TEST (Discriminate)
    {
      id: 'test_cross_origin',
      parentId: 'root',
      label: 'Cross-Origin Dispatch Test',
      category: 'TEST',
      tagline: 'Send request with untrusted Origin header to test origin isolation',
      thinkAbout: [
        'Action: Dispatch request with Origin: https://attacker.local and valid session cookie.',
        'If server accepts request with 200 OK and mutates state -> Refutes Origin header validation (H2). Supports session-only authentication (H1).'
      ],
      diagnosticQuestions: [
        'Does the server reject requests with unexpected Origin values?'
      ],
      evidenceToInspect: [
        {
          title: 'Cross-Origin Request Probe',
          type: 'http',
          snippet: `POST /api/profile/email HTTP/1.1\nHost: app.local\nOrigin: https://attacker.local\nReferer: https://attacker.local/exploit.html\nCookie: session_id=sess_user_9921\nContent-Type: application/x-www-form-urlencoded\n\nemail=probe@attacker.local`
        }
      ],
      discriminatingExperiment: {
        action: 'Send POST with Origin: https://attacker.local and valid session cookie',
        predictionIfTrue: 'Server responds 200 OK and updates email despite foreign origin',
        predictionIfFalse: 'Server responds 403 Forbidden or 400 Bad Request',
        whyInformative: 'Directly discriminates whether the server inspects the Origin header'
      },
      pitfalls: [
        'Testing from localhost and assuming production CORS/SameSite behavior matches.'
      ]
    },
    {
      id: 'test_strip_origin',
      parentId: 'root',
      label: 'Header Stripping Test',
      category: 'TEST',
      tagline: 'Remove Origin and Referer to test header-absence behavior',
      thinkAbout: [
        'Many proxies, browser privacy extensions, and <meta name="referrer" content="no-referrer"> tags strip Origin/Referer headers.',
        'Some applications validate Origin *if present*, but allow requests if Origin is absent!'
      ],
      diagnosticQuestions: [
        'Does the server fail-open when Origin and Referer are omitted?'
      ],
      evidenceToInspect: [
        {
          title: 'Stripped Provenance Probe',
          type: 'headers',
          snippet: `POST /api/profile/email HTTP/1.1\nHost: app.local\n# Origin and Referer deliberately stripped!\nCookie: session_id=sess_user_9921\n\nemail=no_origin@test.local`
        }
      ],
      discriminatingExperiment: {
        action: 'Send POST with Origin and Referer headers completely omitted',
        predictionIfTrue: 'Server executes state change (revealing fail-open on absent headers)',
        predictionIfFalse: 'Server blocks request requiring explicit origin provenance',
        whyInformative: 'Determines whether origin validation can be bypassed by suppressing referrer'
      },
      pitfalls: [
        'Assuming a site that validates Origin on standard requests cannot be bypassed via referrer suppression.'
      ]
    },
    {
      id: 'test_token_differential',
      parentId: 'root',
      label: 'Token Differential Tests',
      category: 'TEST',
      tagline: 'Test omission, empty value, method switch, and cross-session token reuse',
      thinkAbout: [
        'Differential test 1 (Omission): Remove token parameter entirely.',
        'Differential test 2 (Tamper): Change token value by 1 byte -> verify 403.',
        'Differential test 3 (Cross-session): Use a valid token generated by tester account B on tester account A -> tests session binding!'
      ],
      diagnosticQuestions: [
        'Is the anti-CSRF token strictly tied to the active user session in server-side storage?',
        'Does the server skip token validation if the parameter is absent?'
      ],
      evidenceToInspect: [
        {
          title: 'Differential Token Test Matrix',
          type: 'checklist',
          snippet: `Test 1: csrf_token=valid_token -> 200 OK (Baseline)\nTest 2: csrf_token=invalid_token -> 403 Forbidden\nTest 3: [csrf_token omitted] -> 200 OK? (Omission bypass!)\nTest 4: csrf_token=account_B_token -> 200 OK? (Session disconnect!)`
        }
      ],
      discriminatingExperiment: {
        action: 'Submit form without csrf_token parameter',
        predictionIfTrue: 'Server processes state change (fails to enforce presence)',
        predictionIfFalse: 'Server rejects with 403 Forbidden',
        whyInformative: 'Separates presence-conditional validation from strict mandatory validation'
      },
      pitfalls: [
        'Only checking if an invalid token fails (which usually passes) without testing omission or session tie.'
      ]
    },

    // 5. EVIDENCE (Calibrate)
    {
      id: 'ev_discipline',
      parentId: 'root',
      label: 'Observation vs Inference',
      category: 'EVIDENCE',
      tagline: 'Maintain strict separation between measured data and conclusions',
      thinkAbout: [
        'OBSERVATION: Request with Origin: evil.com returned 200 OK and database email field changed.',
        'INFERENCE: The application is exploitable via CSRF in real victim browsers.',
        'Why the gap matters: Exploitation also depends on whether the victim\'s browser transmits the cookie! If SameSite=Strict or Lax applies, form POSTs will drop cookies in actual victim browsers.'
      ],
      diagnosticQuestions: [
        'Have I verified browser cookie attachment behavior under cross-site subresource rules?',
        'Am I assuming exploitability based on an API tool (Postman/curl) that doesn\'t enforce browser cookie policies?'
      ],
      evidenceToInspect: [
        {
          title: 'Evidence Calibration Ledger',
          type: 'checklist',
          snippet: `Direct Observation: Server accepted mutated POST request without anti-CSRF token.\nUncertainty Boundary: Does SameSite=Lax prevent cookie transmission on victim browser?\nVerification Step: Test form submission in actual browser across separate origins.`
        }
      ],
      pitfalls: [
        'Testing in curl/Burp with manually added cookies and claiming CSRF without checking browser SameSite policy.'
      ]
    },

    // 6. RECONSTRUCT (Causal Mechanism)
    {
      id: 'recon_causal',
      parentId: 'root',
      label: 'Causal Chain Reconstruction',
      category: 'RECONSTRUCT',
      tagline: 'Map the complete 5-stage causal chain from trigger to state mutation',
      thinkAbout: [
        'Step 1 (Payload Staging): Attacker hosts malicious page with automated trigger.',
        'Step 2 (Coerced Dispatch): Victim visits attacker page while maintaining authenticated session.',
        'Step 3 (Ambient Credential Injection): Browser attaches Cookie based on target domain matching.',
        'Step 4 (Server Conflation): Target application validates session, skips origin provenance check.',
        'Step 5 (Silent Execution): State mutation commits; SOP prevents reading response but mutation has happened.'
      ],
      diagnosticQuestions: [
        'What is the exact point of divergence between intended normal execution and vulnerable cross-origin execution?'
      ],
      evidenceToInspect: [
        {
          title: 'Causal Sequence Diagram',
          type: 'checklist',
          snippet: `[evil.com] -> Coerces request dispatch (<form>, fetch)\n   |\n[Victim Browser] -> Injects ambient session cookie\n   |\n[Server Session Validator] -> Authenticates identity\n   |\n[Server Business Logic] -> Commits email change without intent verification`
        }
      ],
      pitfalls: [
        'Describing the bug as "missing token" rather than explaining the architectural failure of ambient authority.'
      ],
      canonicalReference: {
        conceptOrMechanism: 'mechanism.origin-context-confusion',
        whyItMatters: 'Conflates WHO the user is (identity) with WHAT CONTEXT generated the action (intent).'
      }
    },

    // 7. CAPABILITY (Impact Calibration)
    {
      id: 'cap_primitive',
      parentId: 'root',
      label: 'Capability vs Impact',
      category: 'CAPABILITY',
      tagline: 'Separate the technical primitive from downstream business impact',
      thinkAbout: [
        'PRIMITIVE: The ability to induce an authenticated state-changing HTTP request from an untrusted origin using the victim\'s ambient credentials.',
        'IMPACT: Account takeover, fund transfer, privilege escalation.',
        'Prerequisites: Victim must hold active session, victim must load external link, endpoint must lack secondary confirmation (re-auth password check, email link confirmation).'
      ],
      diagnosticQuestions: [
        'Does the application send a confirmation token to the OLD email address before applying the change?',
        'Does the application require the user\'s current password to update email?'
      ],
      evidenceToInspect: [
        {
          title: 'Capability Calibration Checklist',
          type: 'checklist',
          snippet: `Demonstrated Primitive: Cross-origin state mutation on POST /api/profile/email.\nExploitation Prerequisites: Victim loads attacker page, active session, no re-auth prompt.\nDownstream Impact: Account takeover via password reset redirection if email change is unconfirmed.`
        }
      ],
      pitfalls: [
        'Claiming full Account Takeover when the server sends a confirmation email to the user\'s existing inbox before changing.'
      ]
    },

    // 8. TRANSFER (Portability)
    {
      id: 'transfer_variants',
      parentId: 'root',
      label: 'Cross-Domain Transfer',
      category: 'TRANSFER',
      tagline: 'Apply origin-context reasoning to non-traditional protocols and surfaces',
      thinkAbout: [
        'Cross-Site WebSocket Hijacking (CSWSH): WebSockets use HTTP Upgrade with ambient cookies. SOP does NOT apply to WebSockets! Attacker gains full bidirectional read/write access if server omits Origin check.',
        'GraphQL Endpoints: Often accept POST requests with Content-Type: text/plain or URL query parameters.',
        'Login CSRF: Forcing victim into attacker\'s account (recording victim\'s searches or payment methods).',
        'Mobile WebViews: Embedded WebViews that ignore SameSite=Lax defaults.'
      ],
      diagnosticQuestions: [
        'Does the WebSocket handshake at wss://target.com/ws validate the HTTP Origin header during HTTP 101 Switching Protocols?',
        'Does the GraphQL /graphql endpoint accept simple POST or GET mutations?'
      ],
      evidenceToInspect: [
        {
          title: 'CSWSH Handshake Archetype',
          type: 'http',
          snippet: `GET /ws/orders HTTP/1.1\nHost: trade.apex.local\nUpgrade: websocket\nConnection: Upgrade\nOrigin: https://evil.local\nCookie: session_id=sess_trader_5502\nSec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==\nSec-WebSocket-Version: 13`
        }
      ],
      pitfalls: [
        'Assuming CSRF is limited to legacy HTML form submissions.'
      ]
    }
  ]
};
